<a href="https://colab.research.google.com/github/luiz-bcardoso/UFN-DataScience/blob/main/aulas_robertson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Vetor: {vetor}")
print(f"Tipo: {type(vetor)}")
print(f"Tipo dos elementos: {vetor.dtype}")
print(f"Dimensões: {vetor.ndim}")
print(f"Formato: {vetor.shape}")
print(f"Quantidade de elementos: {vetor.size}")
print(f"Quantidade de bytes: {vetor.nbytes}")
print(f"Bytes por elemento: {vetor.itemsize}")

Vetor: [1 2 3 4 5 6 7 8 9]
Tipo: <class 'numpy.ndarray'>
Tipo dos elementos: int64
Dimensões: 1
Formato: (9,)
Quantidade de elementos: 9
Quantidade de bytes: 72
Bytes por elemento: 8


In [4]:
matriz = np.array([[1, 2, 3], [4, 2, 6], [7, 8, 9]])
print(f"Vetor: {matriz}")
print(f"Tipo: {type(matriz)}")
print(f"Tipo dos elementos: {matriz.dtype}")
print(f"Dimensões: {matriz.ndim}")
print(f"Formato: {matriz.shape}")

Vetor: [[1 2 3]
 [4 2 6]
 [7 8 9]]
Tipo: <class 'numpy.ndarray'>
Tipo dos elementos: int64
Dimensões: 2
Formato: (3, 3)


In [5]:
#Obter o valor minimo, maximo, soma, média, mediana e desvio padrão
print(f"Vetor: {vetor}")
print(f"Valor mínimo: {vetor.min()}")
print(f"Valor máximo: {vetor.max()}")
print(f"Soma: {vetor.sum()}")
print(f"Média: {vetor.mean()}")
print(f"Mediana: {np.median(vetor)}")
print(f"Desvio padrão: {vetor.std()}")



Vetor: [1 2 3 4 5 6 7 8 9]
Valor mínimo: 1
Valor máximo: 9
Soma: 45
Média: 5.0
Mediana: 5.0
Desvio padrão: 2.581988897471611


In [6]:
#Vetor de preços aleatorios
precos = np.random.rand(100000000) * 10000
precos = np.round(precos, 2)
print(precos)
print(precos.size)

[3810.77 7009.16 8006.49 ... 4796.24  355.13 2171.71]
100000000


In [7]:
# Fazendo aumento de 20% usando python puro
nova_tabela_precos = []
%time
for preco in precos:
    novo_preco = preco * 1.20
    nova_tabela_precos.append(novo_preco)

CPU times: total: 0 ns
Wall time: 5.48 μs


In [8]:
# Fazendo aumento de 20% usando numpy
nova_tabela_precos = []
%time
nova_tabela_precos = precos *1.20
# numpy is poggers

CPU times: total: 0 ns
Wall time: 5.25 μs


In [9]:
vendas = np.array([
    #seg, ter, qua, qui, sex, sab, dom
    [50, 60, 55, 58, 80, 120, 100], # loja 1
    [40, 45, 50, 48, 70, 110, 90],  # loja 2
    [35, 38, 40, 42, 60, 105, 85],  # loja 3
])

print(vendas)

[[ 50  60  55  58  80 120 100]
 [ 40  45  50  48  70 110  90]
 [ 35  38  40  42  60 105  85]]


In [10]:
#Vendas da loja 2 na quinta feira
print(vendas[1][3])

#Vendas da loja 3 na segunda feira
print(vendas[2][0])

#trocar valor da loja 3 no domingo
vendas[2][6] = 88


48
35


In [11]:
#total de vendas por loja
print(vendas.sum(axis=1)) # 1 : coluna

#total de vendas por dia para cada loja
print(vendas.sum(axis=0)) # 0 : linha

[523 453 408]
[125 143 145 148 210 335 278]


In [15]:
#média de vendas por loja
print(np.round(vendas.mean(axis=1),2)) # 1 : coluna

#média de vendas por dia para cada loja
print(np.round(vendas.mean(axis=0),2)) # 0 : linha

[74.71 64.71 58.29]
[ 41.67  47.67  48.33  49.33  70.   111.67  92.67]


In [21]:
#medianda de vendas das lojas
print(np.median(vendas))

58.0
