### Exercício: Análise de Vendas de Sorvetes nas Férias de Verão.

Você é um analista de dados contratado por uma franquia de sorveterias chamada
GelatoTech. Durante as férias de verão, eles monitoraram as vendas de sorvetes em 4 lojas
diferentes, ao longo de 7 dias consecutivos (de segunda a domingo).

---

Sua missão é analisar os dados de vendas e extrair insights importantes para a diretoria da
empresa.

In [3]:
import numpy as np

In [4]:
# Vendas em R$ mil (linhas: lojas | colunas: dias da semana)
vendas_sorvete = np.array([
[12, 15, 14, 10, 20, 35, 30], # Loja 1
[10, 11, 12, 9, 18, 32, 28], # Loja 2
[ 9, 8, 11, 10, 19, 30, 25], # Loja 3
[13, 14, 13, 11, 21, 36, 31] # Loja 4
])

dias = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Dom']
lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']

1. Qual loja vendeu mais no total da semana?

In [34]:
venda_total_semana = []

venda_total_semana = np.sum(vendas_sorvete, axis=1)
print(venda_total_semana)
print(np.max(venda_total_semana))

[136 120 112 139]
139


2. Qual foi o dia de maior faturamento geral?

In [45]:
indice_dia_maior_faturamento = np.argmax(np.sum(vendas_sorvete, axis=0))
print(indice_dia_maior_faturamento)

5


3. Qual foi a média de vendas por loja ao longo da semana?

In [44]:
media_vendas_semana = np.mean(vendas_sorvete, axis=0)
print(np.round(media_vendas_semana, 2))

[11.   12.   12.5  10.   19.5  33.25 28.5 ]


4. Qual loja teve a menor mediana de vendas diárias?

In [49]:
mediana_vendas_diaria = np.median(vendas_sorvete, axis=0)
print(np.round(mediana_vendas_diaria, 2))

[11.  12.5 12.5 10.  19.5 33.5 29. ]


5. Quantos dias a Loja 1 vendeu mais do que R$ 25 mil?

In [63]:
dias_loja_vendeu_mais_25 = np.count_nonzero(vendas_sorvete[0] > 25) #cursed af 💀
print(dias_loja_vendeu_mais_25)

2


6. Crie uma nova matriz com as vendas acrescidas de 10% (simulando um reajuste
nos preços dos sorvetes)

In [66]:
vendas_sorvete_110 = vendas_sorvete *1.10
print(vendas_sorvete_110)

[[13.2 16.5 15.4 11.  22.  38.5 33. ]
 [11.  12.1 13.2  9.9 19.8 35.2 30.8]
 [ 9.9  8.8 12.1 11.  20.9 33.  27.5]
 [14.3 15.4 14.3 12.1 23.1 39.6 34.1]]


**DESAFIO:** A empresa quer premiar a loja que mais cresceu nas vendas do final de semana (Sábado e Domingo).

Calcule o total do fim de semana para cada loja e indique a campeã.

In [73]:
print(vendas_sorvete)
vendas_sabado_domingo = np.sum(vendas_sorvete[:,5:7], axis=0)
print(vendas_sabado_domingo)

[[12 15 14 10 20 35 30]
 [10 11 12  9 18 32 28]
 [ 9  8 11 10 19 30 25]
 [13 14 13 11 21 36 31]]
[133 114]
